CREATE TABLE goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    target_date DATE NOT NULL,
    description VARCHAR(150),
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE study_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id BIGINT NOT NULL,
    recorded_at DATE NOT NULL,
    content VARCHAR(100) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    CONSTRAINT fk_study_records_goal
        FOREIGN KEY (goal_id)
        REFERENCES goals (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_study_records_goal_id ON study_records (goal_id);
CREATE INDEX idx_study_records_goal_id_recorded_at ON study_records (goal_id, recorded_at DESC);
